#!/usr/bin/python3
# Description
< 
Replace the line above with a short description of the script.  Sometimes
people use multiple lines todescribe the inputs and expected outputs.
>

# Versioning
# Ski-20130930: initial version
<
Replace the line above with the date you finished and your name
As you revise it, add in more lines with what you changed
>

# Set up initial variables and imports
import sys
SITES = ['bhs','ah','lms']
MAIL_SERVER = 'smtp.google.com'
< 
Put any global or initial variables here. This is the only place where folks
should make quick changes to the script such as using a different mail server
account.  Change/remove the example lines above as needed 
>

# Main routine that is called when script is run
def main():
  """What does this function do"""
<
For each function, put in a doc string that tells me what the function is
suppose to do. For each block of code such as a loop, large if statement, 
etc, put a single line comment describing why it is needed
>
  # Get the messages and process them
<
The functions code goes here. Use comments in the code to explain what
large blocks of it do or for something you may not remember how it works
>


# Subroutines
<
The subroutines called by the main function are listed here
>
def sub1(message):
  """What does this function do"""


# Run main() if script called directly, else use as a library to be imported
if __name__ == "__main__":
        main()
